apiVersion: v1
kind: Service
metadata:
  name: zoropay-frontend-service
  namespace: zoropay
spec:
  type: NodePort
  selector:
    app: zoropay-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007